### PR TITLE
Index page has been styled. "Customer" column has been added

### PR DESCRIPTION
**Pull request by BUSHA**
## Overview

- [x] customer column has been added to the index page
- [x] index page has been styled
- [x] tests updated

Refs: LM-none

### CODE REVIEW

**Comment by BUSHA** [comment]
@veelenga Could you please to help me to cover the new code with tests and to handle png file name variable in a more unified way?

**Comment by veelenga** [comment]
Thanks @BUSHA . I will extend this PR

**Comment by veelenga** [comment]
@BUSHA add env var, so the end user can control the number of columns, filenames and column names. Example:

```
BASE64_COLUMNS="Customer=default-logo.png" node server.js
```

**Comment by BUSHA** [comment]
@veelenga thank you! An awesome and universal solution!

**Review by denis90 — APPROVED** [review]
LGTM

**Pull request merged**
